name: last nest buile # 현제 제목

on: # 이벤트를 등록
  push: # push 이벤트가 발생하면 
    branches: # branches 어떤 브랜치에 이벤트가 일어났을때 작업을 동작시킨다.
      - main

jobs: # 작업의 단위
  soonBuild: # 식별자
    runs-on: ubuntu-latest # 러너에서 사용할 os (latest -> 최신 버전 사용하겠다.)

    steps: # 작업의 가장 작은 단위
      - name: checkout # 작업의 작은 단위의 이름
        uses: actions/checkout@v4 # 레포지토리를 체크아웃 할 수 있게 도와주는 라이브러리
        # 브랜치에 있는 내용을 클론해온다. 워크플로우에 복사해온다.

      - name: set up node # uses 라이브러리를 사용할 것을 가져오고 with는 라이브러리의 속성 설정
        uses: actions/setup-node@v4 # 노드 버전을 가져오고
        with:
          node-version: '20' # 20 버전의 노드 런타임 환경을 제공

      - name: test # 의존성을 설치하기 전에 폴더 구조 확인 pwd 현재 작업환경의 경로
        run: | # 코드를 줄내림해서 여러줄을 쓸때 사용 (한줄은 필요없음)
          ls
          pwd

      - name: npm install # 의존성 설치
        run: npm install

      - name: build nestjs #빌드
        run: npm run build

      - name: build test # 빌드 파일 확인
        run: |
          ls
          pwd
          cd dist
          ls
          pwd